### ISSUE TITLE
Add conditional move / select instruction

### ISSUE THREAD

**Issue by moonheart08** [ladystarbreeze/mina-isa#6]
Generally a helpful instruction to have as, unlike a branch, it doesn't have any penalties or prediction requirements as it doesn't modify the instruction pointer. Good for producing branch-free output, and directly maps to a common compiler operation (LLVM has a SELECT instruction in it's IR that exactly matches ISEL/FSEL semantics, GCC has conditional execution in it's RTL)
If/when vectors are introduced, a vector version of this should ideally use a bitmask and select on a per-value basis.
```
Integer Select
ISEL rD, rS1, rS2
If T == 1, rS1 is moved to rD, else rS2 is moved to rD.

Float Select
FSEL fD, fS1, fS2
if T == 1, fS1 is moved to fD, else fS2 is moved to rD.
```

**Comment by moonheart08** [comment]
Note: I'm commenting this with full awareness of MT and MF. ISEL is more capable and would be a full replacement for both.

**Comment by moonheart08** [comment]
As someone was confused, the following sequences would replace MT/MF:
`MT rD, rS` becomes `ISEL rD, rS, rD`
`MF rD, rS` becomes `ISEL rD, rD, rS`

**Comment by ladystarbreeze** [comment]
That's actually a pretty good idea. Saves encoding space and is a more powerful version of MT/MF. I'll replace them with ISEL ASAP, thanks.

**Comment by ladystarbreeze** [comment]
MT and MF were replaced with SEL in https://github.com/ladystarbreeze/mina-isa/commit/80b5b3cf6c4cf1c7e5852a4a6389df8eed783c1d.
